config/routes.rb
Rails.application.routes.draw do
  resources :posts
  post '/callback' => 'linebot#callback'
  # get "/auth/:provider/callback" => "sessions#callback"
  devise_for :users, controllers: {
    # omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    omniauth_callbacks: "omniauth_callbacks",
    passwords: "users/passwords" #ゲスト
    # sessions: "users/sessions"
  }
  get 'rooms/show'
  get 'welcome/home'
  resources :rooms, only: %i[show]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  resources :users
  resources :events
  root 'welcome#index'
  
  resource :retirements, only: %i[new create]

  resources :events do
    resources :tickets
    member do
      post '/ticket/:event_id' => 'tickets#ticket', as: 'ticket'
      delete '/ticket/:event_id' => 'tikets#unticket', as: 'unticket'
    end
  end
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <%= link_to "助っ人マスター", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">
        <span></span>
        <span></span>
        <span></span>
      </span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'ホーム',  welcome_home_path, class: 'nav-link'%>
          </li>
          <!-- /.navbar-nav -->
          <li class="nav-item active">
            <%= link_to 'アルバイトを追加', new_event_path, class: 'nav-link'%>
          </li>

          <div class="dropdown nav-drop">
            <li class="nav-item active" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            一覧ページ
            </li>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'マイページ', user_path(id: current_user.id), class: 'nav-link'%>
            <div class="dropdown-divider"></div>
            <%= link_to "人材", users_path, class: "nav-link" %>
            <%= link_to 'アルバイト', events_path, class: 'nav-link'%>
            </div>
          </div>

          <li class="nav-item active">
            <%= link_to "ログアウト",  new_retirements_path,  class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to 'ログイン', new_user_session_path, class: 'nav-link'%>
          </li>
          <li class="nav-item active">
            <%= link_to 'ユーザー登録', new_user_registration_path, class: 'nav-link' %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>