config/routes.rb
Rails.application.routes.draw do
  resources :posts
  post '/callback' => 'linebot#callback'
  # get "/auth/:provider/callback" => "sessions#callback"
  devise_for :users, controllers: {
    # omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    omniauth_callbacks: "omniauth_callbacks",
    passwords: "users/passwords" #ゲスト
    # sessions: "users/sessions"
  }
  get 'rooms/show'
  get 'welcome/home'
  resources :rooms, only: %i[show]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  resources :users
  resources :events
  root 'welcome#index'
  
  resource :retirements, only: %i[new create]

  resources :events do
    resources :tickets
    member do
      post '/ticket/:event_id' => 'tickets#ticket', as: 'ticket'
      delete '/ticket/:event_id' => 'tikets#unticket', as: 'unticket'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
  end

  def home
    @events = Event.order(:start_time)
    @users = User.paginate(page: params[:page], per_page: 5)
    @rooms = Room.all.order(:id)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<h1 class="text-center">アルバイト表</h1>
<div class="box">
  <div class="box-inner">
  <div class="event-user">
    <%= render "layouts/user_page"%>
  </div>
  <!-- /.event-user -->
  </div>
  <!-- /.box-inner -->
</div>
<!-- /.box -->
<div class="main">
  <div class="event-container">
    <ul class="list-group">
      <%= month_calendar events: @events do |date, events| %>
        <%= date.day %>
        <% events.each do |event| %>
        <div>
          <%= link_to event.name.truncate(5), event %>
        </div>
        <% end %>
      <% end %>
      <%= link_to '予定を書く', new_event_path, class: "btn btn-secondary btn-lg" %>
    </ul>
    <!-- /.list-group -->
  </div>
  <!-- /.event-container -->
</div>
<!-- /.main -->

app/views/welcome/index.html.erb
<div class="home_container">
  <section id="heading">
    <div class="row">
      <div class="d-flex flex-column justify-content-center example">
        <div class="top-title"><h2 class="text-center text-lg-start" style="font-weight: bold;">目指せ助っ人マスター！</h2></div>
        <!-- /.top-title -->
        <div class="top-content"><img class="img-fluid" src="/assets/roof_log.png" alt=""></div>
        <div class="sign-box">
          <div class="sign-content">
          <% if user_signed_in? %>
          <div class="text-center text-lg-start">
              <%= link_to '早速募集をしてみよう！！', new_event_path, class: 'btn btn-outline-danger rounded-pill'%>
              </div>
          <% else %>
            <div class="text-center text-lg-start">
              <%= link_to "今すぐはじめる", new_user_registration_path, class: 'btn btn-outline-dark rounded-pill' %>
              <%= link_to "LINEでログイン", user_line_omniauth_authorize_path, method: :post, class: 'btn btn-outline-success rounded-pill' %>
              <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: 'btn btn-outline-danger rounded-pill' %>
            </div>
          <% end %>
          </div>
        </div>
        <!-- /.sign-box -->
      </div>
    </div>
  </section>
</div>
<div>
  <section id="about" class="contents">
    <div class="description">
      <h3 style="font-weight: bold;">助っ人マスターとは</h3>
        <p>
          使い方をシンプルした「勤怠管理アプリ」です。<br>
「人手不足で手が空いてる人に助っ人に来て欲しい」<br>「毎度連絡を入れるのが申し訳ない」<br>「常に掲示板的な物に仕事概要を載せって気軽に見れるようにできれば」など、<br>
一つの小さな悩みが解決できると思います。<br>
        </p>
    </div>
  </section>
</div>

<div>
  <section id="about" class="contents">
    <div class="features">
      <h3 style="font-weight: bold;">助っ人マスターの特徴</h3>
        <div class="row">
          <div class="col-lg-4 col-md-6">
            <div class="box-features">
              <h4 class="contents-title">投稿機能</h4>
              <!-- /.contents__title -->
            </div>
            <!-- /.box -->
            <p>
            人材が欲しい仕事があれば投稿すると登録ユーザーに届く。
            </p>
          </div>

          <div class="col-lg-4 col-md-6 mt-4 mt-md-0">
            <div class="box-features">
              <h4 class="contents-title">日数管理機能</h4>
              <!-- /.contents__title -->
            </div>
            <!-- /.box -->
            <p>
            アルバイトの日数、現在何日働いているか一目でわかります。
            人材単価を上げることも可能かも！？
            </p>
          </div>

          <div class="col-lg-4 col-md-6 mt-4 mt-lg-0">
            <div class="box-features">
              <h4 class="contents-title">Googleマップ機能</h4>
              <!-- /.contents__title -->
            </div>
            <!-- /.box -->
            <p>
              指定の現場までルートをGoogleマップと連動しているので可能。
            </p>
            </div>
          </div>
        </div>
    </div>
  </section>
</div>