config/routes.rb
Rails.application.routes.draw do
  resources :posts
  post '/callback' => 'linebot#callback'
  # get "/auth/:provider/callback" => "sessions#callback"
  devise_for :users, controllers: {
    # omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    omniauth_callbacks: "omniauth_callbacks",
    passwords: "users/passwords" #ゲスト
    # sessions: "users/sessions"
  }
  get 'rooms/show'
  get 'welcome/home'
  resources :rooms, only: %i[show]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  resources :users
  resources :events
  root 'welcome#index'
  
  resource :retirements, only: %i[new create]

  resources :events do
    resources :tickets
    member do
      post '/ticket/:event_id' => 'tickets#ticket', as: 'ticket'
      delete '/ticket/:event_id' => 'tikets#unticket', as: 'unticket'
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if @event.errors.any? %>
  <div class="alert">
    <ul>
      <% @event.errors.full_messages.each do |message|  %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_event-status.html.erb
<div class="col-4">
    <% if @event.created_by?(current_user) %>
      <%= link_to "編集", edit_event_path(@event), class: "btn btn-info btn-lg btn-block" %>
      <%= link_to "削除", event_path(@event),  method: :delete, data: { confirm: "投稿を削除して大丈夫ですか？" }, class: "btn btn-danger btn-lg btn-block" %>
      
      <%= link_to "送る", callback_path(@event), method: :post, data: { confirm: "送信しますか？" }, class: "btn  btn-lg btn-block btn-success" %>
      
    <% end %>
    <% if user_signed_in? == @ticket.nil? %>
      <button class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#createTicket">
        参加
      </button>
      <div class="modal fade" id="createTicket">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="dialogHeader">参加コメント</h4>
              <button class="close" type="button" data-dismiss="modal" &times;>
              </button>
              <!-- /.close -->
              <!-- /.modal-title -->
            </div>
            <!-- /.modal-header -->
            <%= form_with(model: @event.tickets.build, url: event_tickets_path(@event)) do |f| %>
              <div class="modal-body">
                <div id="createTicketErrors"></div>
                <%= f.text_field :comment, class:  "form-control" %>
              </div>
              <!-- /.modal-body -->
              <div class="modal-footer">
                <button class="btn btn-default" type="button" data-dismiss="modal">
                  キャンセル
                </button>
                <%= f.button "送信", class: "btn btn-primary" %>
              </div>
              <!-- /.modal-footer -->
            <% end %>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal fade -->
    <% else %>
      <%= link_to "キャンセル", event_ticket_path(@event), method: :delete, class: "btn btn-warning btn-lg btn-block" %>
    <% end %>
    <hr>
    <div class="card md-2">
      <h5 class="card-header">参加者</h5>
      <!-- /.card-header -->
      <ul class="list-group list-group-flush">
        <%  @tickets.each do |ticket| %>
          <li class="list-group-item">
            <% if ticket.user %>
              <%= image_tag ticket.user.image_owner, width: 40, height: 40 %>
              <%= "#{ticket.user.name}" %>
              <%= ticket.comment %>
            <% else %>
              退化したユーザー
            <% end %>
          </li>
          <!-- /.list-group-item -->
        <% end %>
      </ul>
      <!-- /.list-group list-group-flush -->
    </div>
    <!-- /.card md-2 -->
  </div>
  <!-- /.col-4 -->

app/views/layouts/_flash_messages.html.haml
- flash.each do |msg_type, msg|
  #alert{:class => "alert alert-#{msg_type}", :role => "alert"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    = msg

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer_fixed">
  <p>©️ 2021 — Silver's kG</p>
  </div>
</footer>

app/views/layouts/_side-bar.html.erb
<div class="side-bar">
  <section class="side-bar__group">
    <h2 class="side-bar__group__title"></h2>
    <li class="side-bar__group__list">
      <%= link_to "", "#" %>
    </li>
    <li class="side-bar__group__list">
      <%= link_to "", "#" %>
    </li>
  </section>
</div>

<% @user.ticket_events.each do |event|  %>
  <li>
    <%= link_to event_path(event), class: "main__table__list__item" do %>
      <figure>
       
      </figure>
      <div class="main__table__list__item__body">
        <div class="main__table__list__item__body__text">
          <%= event.name %>
        </div>
        <br>
          <%= event.name %>
        <i class="fas fa-chevron-right"></i>
      </div>
    <% end %>
  </li>
<% end %>

app/views/layouts/_user_page.html.erb
<h5>ログインユーザー</h5>
<div class="event-user-container">
  <table>
    <thead class="text-center">
    <tbody class="text-center">
        <% @users.each do |user| %> 
          <div class="box-user">
              <% if user.image_url == "" %>
                <%= image_tag "roof_log.png", width: 70, height: 60, class: "image_icons" %>
              <% else %>
                <%= image_tag user.image_url, width: 70, height: 60, class: "image_icons" %>
              <% end %>
              <% if current_user %>
                <%= link_to user.name, user %>
              <% else %>
                <%= user.id %>
              <% end %> 
          </div>
        <% end %>
    </tbody>
    </thead>
  </table>
  <% if User.count > 5%>
  <%= link_to "他のログインユーザーを見る 他ユーザー数#{User.count  - 5}人", users_path %>
  <% end %>
</div>
<!-- /.event-user-container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EventsApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header class="fixed-top">
      <%= render 'shared/header' %>
  </header>
  <div class="base-container">
    <div class="container-fluid py-5 mw-md">
      <% if flash.notice %>
        <div class="alert alert-success">
      <%= flash.notice %>
        </div>
      <% end %>
      <% if flash.alert %>
        <div class="alert alert-danger">
          <%= flash.alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
  <!-- /.base-container -->
</body>

<%= render 'layouts/footer'%>

</html>